using System.IO;
using System.Text;
using WindowsGSH.Core.Modules;

namespace WindowsGSH.Modules.BlankSteamTemplate;

// Minimal C# module template.
//
// module.json supplies metadata, config fields, Steam install settings, launch
// path/arguments, backup targets, addons, and API actions. Override only the
// behavior that is genuinely game-specific.
//
// Remove this C# file entirely if the game needs no custom behavior — a
// manifest-only module (type: json) works fine for servers that only need
// a start executable and config fields.
public sealed class BlankSteamTemplateModule : ManifestBackedGameServerModule
{
    // Set supportsQuery: true and implement QueryAsync below when the game
    // has a real query protocol (Source A2S, Unreal 2, FiveM, EOS, etc.).
    // Set supportsRcon: true and implement ExecuteRconCommandAsync below
    // when the game supports Source RCON or an equivalent command API.
    public override ModuleCapabilities Capabilities => Manifest.ToCapabilities(
        supportsQuery: false,
        supportsRcon: false);

    // Return the connection info shown in the server list.
    // Change the keys to match what you defined in configFields.
    public override ServerDisplayInfo GetDisplayInfo(ServerInstance instance)
    {
        return new ServerDisplayInfo(
            IpAddress: GetSetting(instance, "network.ip", "0.0.0.0"),
            Port: GetSetting(instance, "network.port", "27015"),
            MaxPlayers: GetSetting(instance, "server.maxPlayers", "16"));
    }

    // Write any config files the game server reads at startup.
    // Called before start and after the user saves settings.
    // Delete this override if the game does not use config files
    // (i.e., all configuration is passed as command-line arguments).
    public override Task WriteConfigFileSettingsAsync(ServerInstance instance, CancellationToken cancellationToken)
    {
        var configDirectory = Path.Combine(instance.InstallPath, "config");
        Directory.CreateDirectory(configDirectory);

        var config = new StringBuilder();
        config.AppendLine("# Config generated by WindowsGSH");
        config.AppendLine($"server_name={GetSetting(instance, "server.name", Name)}");
        config.AppendLine($"server_port={GetSetting(instance, "network.port", "27015")}");
        config.AppendLine($"max_players={GetSetting(instance, "server.maxPlayers", "16")}");
        config.AppendLine($"public={GetSetting(instance, "server.public", "true")}");
        File.WriteAllText(Path.Combine(configDirectory, "server.cfg"), config.ToString());

        return Task.CompletedTask;
    }

    // Return the path to the folder where the server writes log files.
    // WindowsGSH uses this for log display and crash diagnostics.
    // Return null if the server does not write log files.
    public override string? GetConsoleLogPath(ServerInstance instance)
    {
        return Path.Combine(instance.InstallPath, "logs");
    }

    // Uncomment and implement QueryAsync to return live player and status data.
    // Also set supportsQuery: true in Capabilities above.
    //
    // public override async Task<ServerQueryResult?> QueryAsync(
    //     ServerInstance instance, CancellationToken cancellationToken)
    // {
    //     var port = int.Parse(GetSetting(instance, "network.queryPort", "27015"));
    //     // Use one of the built-in query clients, for example:
    //     // return await SourceQueryClient.QueryAsync(instance.DisplayInfo.IpAddress, port, cancellationToken);
    //     return null;
    // }

    // Uncomment and implement ExecuteRconCommandAsync to send commands via RCON.
    // Also set supportsRcon: true in Capabilities above.
    //
    // public override async Task<string?> ExecuteRconCommandAsync(
    //     ServerInstance instance, string command, CancellationToken cancellationToken)
    // {
    //     var port = int.Parse(GetSetting(instance, "network.port", "27015"));
    //     var password = GetSetting(instance, "rcon.password", string.Empty);
    //     // Use SourceRconClient or your own implementation here.
    //     return null;
    // }
}
